app:
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://iec3project.mysql.database.azure.com:3306/iec3project
      username: 'adminroot'
      password: 'Qwerty123'
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always


